### ISSUE TITLE
error by calling updateSubresourceData

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#86] opened 2018-06-29 23:50 UTC
when I call updateSubresourceData(texture,0,data,uvec3(11, 2, 0),uvec3(7, 7, 1)), an error popped up.

D3D12 ERROR: ID3D12CommandList::CopyTextureRegion: D3D12_SUBRESOURCE_FOOTPRINT::RowPitch must be a multiple of 256 (aka. D3D12_TEXTURE_DATA_PITCH_ALIGNMENT) and greater or equal to the pitch implied by the width. RowPitch is 28, and must be greater or equal to 28 when D3D12_SUBRESOURCE_FOOTPRINT::Width is 7 and D3D12_SUBRESOURCE_FOOTPRINT::Format is R8G8B8A8_UNORM. [ RESOURCE_MANIPULATION ERROR #868: COPYTEXTUREREGION_INVALIDSRCROWPITCH]

The texture is 2d texture 256*256 with format RGBA8 Unorm.

**Comment by nbenty** [comment] 2018-06-30 00:37
I root caused the bug, will fix it shortly

**Comment by nbenty** [comment] 2018-06-30 00:44
Fixed in `dev-3.1`

**Closed by nbenty** 2018-06-30 00:44 UTC
