### ISSUE TITLE
SceneEditor crashes on scene load in Ubuntu 16.04

### ISSUE THREAD

**Issue by johnfettig** [NVIDIAGameWorks/Falcor#100] opened 2018-07-17 19:37 UTC
Trying to load Media/Arcade/Arcade.fscene in the scene editor, it throws an error:

```
Program Linkage failed.

Program with Shaders:
Framework/Shaders/SceneEditor.slang/*editorVs*//*editorPs*/

ERROR: /path/to/Bin/Data/DefaultVS.slang:78: 'uint' : must be qualified as flat in
ERROR: /path/to/Bin/Data/DefaultVS.slang:79: '' : compilation terminated
ERROR: 2 compilation errors. No code generated.
```

Maybe this is a bug in slang. ForwardRenderer opens the scene OK, which is strange since it also depends on DefaultVS.

**Comment by KaChen3000** [comment] 2018-07-20 21:43
I have the same problem. There seems to be two problems:
a. the error message is not pointing to the correct slang file with error. The real problem is in SceneEditor.slang, where EditorVSOut is defined as below.
struct EditorVSOut
{
    VertexOut vOut;

#ifdef PICKING
    uint drawID : DRAW_ID;  // Causing crash in slang
#endif

#ifdef CULL_REAR_SECTION
    float3 toVertex : VERTEX_DIR;
#endif
};

b. slang fails to add flat in for uint drawID when translating it into glsl, which in turns  causes compile error in glslang.

for the time being, i changed uint drawID to float drawID and it seems to be working. but a real fix will be nice to have. thanks.

**Comment by nbenty** [comment] 2018-07-24 17:02
@tfoleyNV Is that a Slang or glslang issue? It works on our Linux machine (Ubuntu 17.x)

**Comment by tfoleyNV** [comment] 2018-07-24 17:07
This is a Slang issue, yes. We have some code that is supposed to add the `flat` qualifier where required, but it must not be triggering for this stuff.

**Comment by tfoleyNV** [comment] 2018-07-25 17:05
I can reproduce this failure on Windows with Vulkan, so it doesn't seem to be specific to Linux. I will be trying to get a fix for this implemented in Slang today, after which it would be up to the Falcor team to integrate the new version of Slang into a future release.

**Comment by nbenty** [comment] 2018-07-25 17:52
@kyaoNV Please merge it into the `dev-3.0.6` branch when it's ready

**Comment by tfoleyNV** [comment] 2018-07-25 19:12
shader-slang/slang#619 is the pull request that should fix the underlying Slang issue. I've confirmed that with that fix the SceneEditor sample runs fine with Vulkan (on Windows). I'll update here when that PR is merged and incorporated into a release.

**Comment by nbenty** [comment] 2018-07-26 19:10
@tfoleyNV Is that fix ready?

**Comment by tfoleyNV** [comment] 2018-07-26 20:37
@nbenty Getting things committed and tested right now. Hopefully can have a release ready some time this afternoon.

**Comment by kyaoNV** [comment] 2018-07-28 00:37
Slang update is now on `master`

**Closed by kyaoNV** 2018-07-28 00:37 UTC
