### ISSUE TITLE
GLSL shader compilation issues on AMDGPU Pro on Linux..

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Falcor#31] opened 2017-12-15 23:38 UTC
you can see glsl shader fails using RX Vega and amdgpu pro 17.50 driver on Ubuntu 17.10

see:
![er](https://user-images.githubusercontent.com/669305/34064582-53c48394-e1fa-11e7-9244-4ad2a20fc875.png)

**Comment by nbenty** [comment] 2017-12-16 03:28
Adding @tfoleyNV 
The fact that it's platform dependent suggests that the compilation error comes from the driver and not `glslang`. AFAIK `glslang` is the reference GLSL->SPIR-V compiler, that makes me wonder if that's a driver bug or a SPIR-V issue.

A simple fix would be to change the '1' to `1.0f` but we have many places in the code where we use integer literals to initialize floats.
@tfoleyNV  - do you remember if GLSL allows float initialization using integers? Can Slang help with automatic conversion of int literals to float literals for `Slang` files?

**Comment by oscarbg** [comment] 2017-12-17 05:22
Two comments:
1)just tested same build on Nvidia GPU and have same issue so it's not a AMD GPU driver issue..
seems current master code builds on Linux but any sample fails to run with same error even on Nvidia binary Unix driver (387.34)..
2) more mad is that even changing 1 to 1.0f on this line still reports same error:
changed shader both in:
$builddir/Data/Framework/Shaders
Falcor/Framework/Source/Data/Framework/Shaders
locations.. so are this slang files in same way included inside the binary file? so that modifying this shader files makes no effect?
thanks..

**Comment by nbenty** [comment] 2017-12-17 05:38
We do not include the shader files as binaries. The slang files are compiled during load-time. Changing them should definitely have effect on compilation.

If it's not a driver issue, then the error comes from`glslang`. That's even weirder, because the `glslang` library comes packages with Falcor and the same `.so` file works on my machines. 

@oscarbg What version of the Vulkan SDK are you using?

**Comment by oscarbg** [comment] 2017-12-17 07:01
latest Vulkan 1.0.65 SDK

**Comment by oscarbg** [comment] 2017-12-17 23:09
latest Vulkan 1.0.65 SDK..


2017-12-17 6:38 GMT+01:00 nbenty <notifications@github.com>:

**Comment by tfoleyNV** [comment] 2017-12-18 16:27
I'll take this bug.

From reading the description, it *seems* to be a bug related to the GLSL output that Slang is generating from the input `.slang` file. Currently Slang uses the platform's C standard library (`sprintf`) to format floating point literal expressions, and it seems like this is a case where the stdlib on these Unix machines is producing different textual output than on the machines I use for testing.

**Comment by tfoleyNV** [comment] 2017-12-18 18:21
@oscarbg Nir is going to try to reproduce this issue on the test machine for Falcor's Linux build (which is also running Ubuntu 17.10). If it works there, then maybe we can isolate how the configurations differ between those machines.

It might also help me to isolate any possible bug arising from our shader cross-compiler if you could make the following changes and dump some extra information:

In Falcor's `TextRenderer.cpp`, please find the line that currently says:

```c++
GraphicsProgram::SharedPtr pProgram = GraphicsProgram::createFromFile(kVsFile, kFsFile);
```

and replace it with:
```c++
GraphicsProgram::Desc desc;
desc.sourceFile(kVsFile).entryPoint(ShaderType::Vertex)
    .sourceFile(kFsFile).entryPoint(ShaderType::Pixel)
    .dumpIntermediates(true);
GraphicsProgram::SharedPtr pProgram = GraphicsProgram::create(desc);
```

If you then run any Falcor sample (I chose `SimpleDeferred`) then it should cause a bunch of files of the form `slang-dump-<number>.<ext>` to be output to the working directory. When I do this on my current machine (running Windows) I get 12 files, because the sample runs successfully.

Only the first file is important for now, and that should be `slang-dump-1.glsl` which should be the GLSL vertex shader code that our shader translator is passing on to the `glslang` reference compiler.

On my machine the output is the following:

```glsl
#version 420

#line 29 "D:/src/Falcor/Bin/x64/Debug/Data/Framework/Shaders/TextRenderer.vs.slang"
                                     layout(binding = 1)

#line 29 "D:/src/Falcor/Bin/x64/Debug/Data/Framework/Shaders/TextRenderer.vs.slang"
                uniform              PerFrameCB
{
mat4x4 gvpTransform;
vec3  gFontColor[2];
};

vec4   transform(vec2 posS){
return ((gvpTransform) * (vec4(
                   posS, 0.50000000000000000000f, float(1))));
}

void main_(vec2 posS, 

 inout vec2 texC, 
 out vec4 posSV){

 posSV = transform(posS);
}
layout(location = 0)
in vec2 SLANG_in_posS;
layout(location = 1)
in vec2 SLANG_in_texC;
layout(location = 0)
out vec2 SLANG_out_texC;
void main(){

#line 41 "D:/src/Falcor/Bin/x64/Debug/Data/Framework/Shaders/TextRenderer.vs.slang"
        vec2 posS;
              vec2 texC;
            vec4 posSV;
posS = SLANG_in_posS;
texC = SLANG_in_texC;
main_(posS, texC, posSV);
SLANG_out_texC = texC;
gl_Position = posSV;
}
```

In this case the output GLSL has been validated so that the implicit cast of `1` to a `float` was made explicit (the `float(1)` expression). Given the error message you are seeing, I'd like to confirm that the output GLSL generated on your machine matches this expected output (modulo the paths in the `#line` directives).

**Comment by nbenty** [comment] 2017-12-18 20:57
It works on my Linux machine. Tim suggested that it might be related to the stdlib version.
My installation uses ` (Ubuntu GLIBC 2.26-0ubuntu2) 2.26`
@oscarbg Do you mind checking if your version matches mine (run `ldd --version`)?

**Comment by oscarbg** [comment] 2017-12-19 03:51
@nbenty same version here:
"ldd (Ubuntu GLIBC 2.26-0ubuntu2) 2.26"

**Comment by oscarbg** [comment] 2017-12-19 04:13
@tfoleyNV 
just made the change and now I see the error:
(notice that the relevant file is called slang-dump-0.glsl instead of slang-dump-1.glsl)

as you can see the problem is not in float(1) (done correctly) but in 0.5f gets translated to 
0,500000000f instead of 0.500000f so instead of a dot puts a comma to declare the this float number.. maybe related to a localization error (I have installed as spanish) and maybe thinks in Spain float numbers can use commas instead of dot
code below:
`#version 420

#line 29 "/home/ivan/Falcor/Bin/Data/Framework/Shaders/TextRenderer.vs.slang"
                                     layout(binding = 1)

#line 29 "/home/ivan/Falcor/Bin/Data/Framework/Shaders/TextRenderer.vs.slang"
                uniform              PerFrameCB
{
mat4x4 gvpTransform;
vec3  gFontColor[2];
};

vec4   transform(vec2 posS){
return ((gvpTransform) * (vec4(
                   posS, 0,50000000000000000000f, float(1))));
}

void main_(vec2 posS, 

 inout vec2 texC, 
 out vec4 posSV){

 posSV = transform(posS);
}
layout(location = 0)
in vec2 SLANG_in_posS;
layout(location = 1)
in vec2 SLANG_in_texC;
layout(location = 0)
out vec2 SLANG_out_texC;
void main(){

#line 41 "/home/ivan/Falcor/Bin/Data/Framework/Shaders/TextRenderer.vs.slang"
        vec2 posS;
              vec2 texC;
            vec4 posSV;
posS = SLANG_in_posS;
texC = SLANG_in_texC;
main_(posS, texC, posSV);
SLANG_out_texC = texC;
gl_Position = posSV;
}`

**Comment by oscarbg** [comment] 2017-12-19 04:22
Ok guys..
that was the problem..
(https://help.ubuntu.com/community/Locale)

> LC_NUMERIC
> How you format your numbers. For example, in many countries a period (.) is used as a decimal separator, while others use a comma (,). 

for me was: LC_NUMERIC="es_ES.UTF-8"

at least for now a simple fix for me is:
LC_NUMERIC=en_US.UTF-8 ./SimpleDeferred 

hope you can permanently fix it for all locales..
many thanks..

**Comment by tfoleyNV** [comment] 2017-12-19 16:39
Perfect. Thank you for helping us isolate this, Oscar.

It looks like I need to read up on how to do locale-independent formatting in C, and then work on a fix.

**Comment by nbenty** [comment] 2018-03-28 05:08
@tfoleyNV Can I close this issue?

**Comment by tfoleyNV** [comment] 2018-03-28 15:21
@nbenty Yes, the underlying Slang problem has been fixed.

**Closed** 2018-03-28 15:21 UTC
