### ISSUE TITLE
Desktop hard lock when closing Forward Renderer

### ISSUE THREAD

**Issue by cusiman7** [NVIDIAGameWorks/Falcor#167] opened 2018-12-04 00:07 UTC
I have a custom scene with a few 8K textures mapped to some geometry. After loading:
* Click the X button to close Falcor (ForwardRenderer)
* Continue to move the mouse back and forth rapidly

Expected: Falcor should close cleanly.
Observed: The Desktop environment locks up and you have to reboot the machine. 

This is very consistent and a 100% repro on my side.

I'm using a Razer Blade laptop with Ubuntu 16.04 and Vulkan.

Here's my GPU and driver versions. I've tried the latest driver and the bug is there as well.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P8     5W /  N/A |    191MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2021      G   /usr/lib/xorg/Xorg                           147MiB |
|    0      4632      G   compiz                                        40MiB |
+-----------------------------------------------------------------------------+
```

I also get this syslog report from Xorg:
```
kern     ERR      kernel:                           [ 1571.912279] INFO: task Xorg:3261 blocked for more than 120 seconds.
kern     ERR      kernel:                           [ 1571.912287]       Tainted: P           OE    4.15.0-39-generic #42~16.04.1-Ubuntu
kern     ERR      kernel:                           [ 1571.912289] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
kern     INFO     kernel:                           [ 1571.912293] Xorg            D    0  3261   3130 0x00400000
kern     WARNING  kernel:                           [ 1571.912297] Call Trace:
kern     WARNING  kernel:                           [ 1571.912308]  __schedule+0x3d6/0x8b0
kern     WARNING  kernel:                           [ 1571.912314]  ? alloc_skb_with_frags+0x5a/0x1e0
kern     WARNING  kernel:                           [ 1571.912318]  schedule+0x36/0x80
kern     WARNING  kernel:                           [ 1571.912322]  schedule_timeout+0x1db/0x370
kern     WARNING  kernel:                           [ 1571.912326]  ? mutex_lock+0x12/0x40
kern     WARNING  kernel:                           [ 1571.912330]  ? unix_stream_read_generic+0x25d/0x960
kern     WARNING  kernel:                           [ 1571.912334]  __down+0x8a/0xe0
kern     WARNING  kernel:                           [ 1571.912339]  down+0x41/0x50
kern     WARNING  kernel:                           [ 1571.912342]  ? down+0x41/0x50
kern     WARNING  kernel:                           [ 1571.912622]  os_acquire_mutex+0x34/0x40 [nvidia]
kern     WARNING  kernel:                           [ 1571.912994]  _nv032888rm+0x5c/0x120 [nvidia]
kern     WARNING  kernel:                           [ 1571.913328]  ? _nv032986rm+0x1c/0x60 [nvidia]
kern     WARNING  kernel:                           [ 1571.913672]  ? _nv001171rm+0x1d1/0x830 [nvidia]
kern     WARNING  kernel:                           [ 1571.914004]  ? rm_ioctl+0x73/0x100 [nvidia]
kern     WARNING  kernel:                           [ 1571.914012]  ? __check_object_size+0x41/0x1a0
kern     WARNING  kernel:                           [ 1571.914237]  ? nvidia_ioctl+0x592/0x740 [nvidia]
kern     WARNING  kernel:                           [ 1571.914463]  ? nvidia_frontend_unlocked_ioctl+0x42/0x50 [nvidia]
kern     WARNING  kernel:                           [ 1571.914468]  ? do_vfs_ioctl+0xa4/0x600
kern     WARNING  kernel:                           [ 1571.914473]  ? do_setitimer+0xe0/0x240
kern     WARNING  kernel:                           [ 1571.914477]  ? SyS_setitimer+0xf1/0x120
kern     WARNING  kernel:                           [ 1571.914481]  ? SyS_ioctl+0x79/0x90
kern     WARNING  kernel:                           [ 1571.914486]  ? do_syscall_64+0x73/0x130
kern     WARNING  kernel:                           [ 1571.914492]  ? entry_SYSCALL_64_after_hwframe+0x3d/0xa2
```

I also have an nvidia-bug-report.log.gz attached here if that helps. 
 
[nvidia-bug-report.log.gz](https://github.com/NVIDIAGameWorks/Falcor/files/2641721/nvidia-bug-report.log.gz)

**Comment by nbenty** [comment] 2018-12-06 21:12
@kyaoNV Can you try and repro it?

**Comment by KaChen3000** [comment] 2019-01-30 18:58
We are seeing more hard lock on ubuntu laptop when closing falcor. Is there any update on that? thanks.

**Comment by nbenty** [comment] 2019-02-06 19:38
I can't reproduce it.
Note that technically Falcor requires Ubuntu 17 which is what are test machines are using.

**Comment by KaChen3000** [comment] 2019-02-19 07:35
It happens quite consistently when we move mouse over the X button on the top left of the window to close it, then right after click that button, wiggle mouse left and right multiple times. Can you try that?

**Comment by kyaoNV** [comment] 2019-02-21 19:56
I cannot repro on Ubuntu 17.10 with driver version 384.130 following those steps. We may be able to try it on 18.04

**Closed** 2023-02-27 10:03 UTC
