### ISSUE TITLE
Package '7za' at version '16.02' is missing from local storage

### ISSUE THREAD

**Issue by mrutyu1987** [NVIDIAGameWorks/Falcor#35] opened 2018-01-12 19:24 UTC
Hi,

Trying to setup the Falcor on Windows system. When I run "update_dependencies.bat" script I',m getting the following error: (Output of the script). is it looking for 7-Zip, have installed the 7-Zip 16.02 version. 

```
Creating directory F:\packman-repo
Fetching python@2.7.6-windows-x86.exe from s3 ...
Connecting to S3 ...
Downloading ...
Unpacking ...
Fetching packman-common@5.0.1.zip from s3 ...
Connecting to S3 ...
Downloading ...
Unpacking ...
Package '7za' at version '16.02' is missing from local storage.
packman(ERROR): Package not found on specified remote servers!
!!! Failure while configuring local machine :( !!!
```

Regards,
MJay

**Comment by nbenty** [comment] 2018-01-12 19:52
@halldorfannar Can you please help debugging this issue?

**Comment by halldorfannar** [comment] 2018-01-12 19:52
Yes, @nbenty will do!

**Comment by halldorfannar** [comment] 2018-01-14 12:57
Should be fixed in pull request #36.

**Comment by mrutyu1987** [comment] 2018-01-16 18:18
Thanks. The script now goes ahead with setup. but fails to download the glm module. Here is the error

```
Package 'glm' at version '0.9.8.4' is missing from local storage.
packman(ERROR): Package not found on specified remote servers!
```

should I open a new issue for this or not required?

Regards,
MJay

**Comment by halldorfannar** [comment] 2018-01-16 19:14
@mrutyu1987 We can just continue using this issue even though I've fixed your original problem. I suspect what you are seeing now is a symptom of the same underlying issue. We haven't been able to reproduce these symptoms internally so I would really appreciate if you apply the following patch to your local environment:

1. Extract the attached zip - it will contain one file: s3transport.py
2. Locate the packman 5.1 package on your local machine.  Browse to `%PM_PACKAGES_ROOT%` (Windows) or `$PM_PACKAGES_ROOT` (Linux). In there you will see a `packman-common` folder. Under that folder you should see a folder named `5.1`.
3. Inside the packman 5.1 package find the s3transport.py file (it should be inside `transport` folder within that package). Replace it with the file provided in the attached zip.
4. Now run the failing process again. You should see new debugging output that prints information about the exception generated, starting with the words `Exception is:`

Please post the debug output here.  Thanks!

* [s3transport.zip](https://github.com/NVIDIAGameWorks/Falcor/files/1636426/s3transport.zip)

**Comment by mrutyu1987** [comment] 2018-01-16 23:43
Here is the debug output:

```
Package 'glm' at version '0.9.8.4' is missing from local storage.
Exception is: An error occurred (403) when calling the HeadObject operation: Forbidden
Exception is: An error occurred (403) when calling the HeadObject operation: Forbidden
packman(ERROR): Package not found on specified remote servers!
```

Regards,
MJay

**Comment by halldorfannar** [comment] 2018-01-17 15:06
@mrutyu1987 Thanks for the quick response. This does seem like an issue with the credentials being passed through.  I have made that specific package publicly readable - to confirm that the issue is indeed with authentication.  Please try again and see if you get the `glm` package now. I would expect the process then to fail on the next package (if my theory is correct).

**Comment by mrutyu1987** [comment] 2018-01-17 18:48
Nope. Issue still persists.

```
Package 'glm' at version '0.9.8.4' is missing from local storage.
Exception is: An error occurred (403) when calling the HeadObject operation: Forbidden
Exception is: An error occurred (403) when calling the HeadObject operation: Forbidden
packman(ERROR): Package not found on specified remote servers!

```

Regards,
MJay

**Comment by halldorfannar** [comment] 2018-01-18 15:40
I'm sorry to hear that.  Could you please apply this patch (follow the instructions above):

[s3transport.zip](https://github.com/NVIDIAGameWorks/Falcor/files/1643411/s3transport.zip)

And share the results here. This should give us more diagnostics and hopefully tell us what's funky with the S3 connection. 

Thanks @mrutyu1987 !

**Closed** 2018-03-28 05:08 UTC

**Comment by VigneshMohan1698** [comment] 2022-10-06 22:36
Was this issue ever fixed? I am running into the same one but after pasting the S3 transport py file I got the following error.
`botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the GetBucketAcl operation: The AWS Access Key Id you provided does not exist in our records.`
